<script setup lang="ts">
/**
 * AppFooter - Custom footer for Lithos
 * 
 * Overrides Docus default footer to show "Generated by Lithos"
 */

const appConfig = useAppConfig()

const links = computed(() => [
  ...Object.entries((appConfig as any).socials || {}).map(([key, url]) => ({
    'icon': `i-simple-icons-${key}`,
    'to': url,
    'target': '_blank',
    'aria-label': `${key} social link`,
  })),
  (appConfig as any).github?.url && {
    'icon': 'i-simple-icons-github',
    'to': (appConfig as any).github.url,
    'target': '_blank',
    'aria-label': 'GitHub repository',
  },
].filter(Boolean))
</script>

<template>
  <UFooter class="border-t border-default">
    <template #left>
      <div class="lithos-footer inline-flex items-center gap-1.5 text-sm text-muted">
        <span>Generated by</span>
        <NuxtLink 
          to="https://jwintz.github.io/lithos" 
          target="_blank" 
          rel="noopener"
          class="lithos-footer-link inline-flex items-center gap-1.5 font-medium text-highlighted hover:text-primary transition-colors"
        ><img src="/logo.svg" alt="Lithos" class="lithos-footer-logo" /><span>Lithos</span></NuxtLink>
      </div>
    </template>

    <template #right>
      <template v-if="links.length">
        <UButton
          v-for="(link, index) of links"
          :key="index"
          size="sm"
          v-bind="{ color: 'neutral', variant: 'ghost', ...link }"
        />
      </template>
      <UColorModeButton />
    </template>
  </UFooter>
</template>

<style scoped>
.lithos-footer-logo {
  height: 1rem;
  width: auto;
  vertical-align: middle;
  filter: none;
}

.dark .lithos-footer-logo {
  filter: invert(1) hue-rotate(180deg);
}

.lithos-footer-link {
  vertical-align: middle;
}
</style>
