<script setup lang="ts">
/**
 * AppFooterLeft - Custom footer for Lithos
 * 
 * Displays "Generated by Lithos" with logo and link to GitHub Pages.
 * Overrides Docus default footer left component.
 */
</script>

<template>
  <div class="lithos-footer flex items-center gap-2 text-sm text-muted">
    <span>Generated by</span>
    <NuxtLink 
      to="https://jwintz.github.io/lithos" 
      target="_blank" 
      rel="noopener"
      class="lithos-footer-link flex items-center gap-1.5 font-medium text-highlighted hover:text-primary transition-colors"
    >
      <img 
        src="/logo.svg" 
        alt="Lithos" 
        class="lithos-footer-logo h-4 w-auto"
      />
      <span>Lithos</span>
    </NuxtLink>
  </div>
</template>

<style scoped>
.lithos-footer-logo {
  filter: none;
}

.dark .lithos-footer-logo {
  filter: invert(1) hue-rotate(180deg);
}
</style>
