<script setup lang="ts">
/**
 * AppFooterLeft - Custom footer for Lithos
 * 
 * Displays "Generated by Lithos" with logo and link to GitHub Pages.
 * Overrides Docus default footer left component.
 */

const config = useRuntimeConfig()
const baseURL = computed(() => config.app.baseURL || '/')

// Helper to resolve paths with base URL
const withBase = (path: string) => {
  const base = baseURL.value.endsWith('/') ? baseURL.value.slice(0, -1) : baseURL.value
  return `${base}${path}`
}
</script>

<template>
  <div class="lithos-footer flex items-center gap-2 text-sm text-muted">
    <span>Generated by</span>
    <NuxtLink 
      to="https://jwintz.github.io/lithos" 
      target="_blank" 
      rel="noopener"
      class="lithos-footer-link flex items-center gap-1.5 font-medium text-highlighted hover:text-primary transition-colors"
    >
      <img 
        :src="withBase('/logo.svg')" 
        alt="Lithos" 
        class="lithos-footer-logo h-4 w-auto"
      />
      <span>Lithos</span>
    </NuxtLink>
  </div>
</template>

<style scoped>
.lithos-footer-logo {
  filter: none;
}

.dark .lithos-footer-logo {
  filter: invert(1) hue-rotate(180deg);
}
</style>
