#!/usr/bin/env node
/**
 * Index Generation Script
 * 
 * Generates a dashboard index.md for vaults that lack one.
 */

import { existsSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, basename, extname } from 'path';

const vaultPath = process.argv[2] || 'content';
const indexPath = join(vaultPath, 'index.md');

if (existsSync(indexPath)) {
  console.log('[generate-index] index.md already exists, skipping.');
  process.exit(0);
}

console.log(`[generate-index] Generating index.md for ${vaultPath}...`);

// 1. Get Top-Level Directories (Spaces)
const dirs = readdirSync(vaultPath, { withFileTypes: true })
  .filter(dirent => dirent.isDirectory() && !dirent.name.startsWith('.'))
  .map(dirent => dirent.name)
  .sort();

// 2. Get Recent Files
// Simple recursive walk to find recent .md files
function getRecentFiles(dir, limit = 10) {
  let results = [];
  const list = readdirSync(dir, { withFileTypes: true });
  
  for (const entry of list) {
    const fullPath = join(dir, entry.name);
    if (entry.name.startsWith('.') || entry.name === 'node_modules') continue;

    if (entry.isDirectory()) {
      results = results.concat(getRecentFiles(fullPath));
    } else if (entry.isFile() && entry.name.endsWith('.md')) {
      const stats = statSync(fullPath);
      results.push({
        name: entry.name.replace('.md', ''),
        path: fullPath,
        mtime: stats.mtime
      });
    }
  }
  return results.sort((a, b) => b.mtime - a.mtime).slice(0, limit);
}

const recentFiles = getRecentFiles(vaultPath);

// 3. Generate Content
let content = `---
title: Home
---

# Welcome to ${basename(vaultPath)}

::callout{type="info"}
This index was auto-generated by Lithos because no \`index.md\` was found.
::

## Spaces

<div class="grid grid-cols-1 sm:grid-cols-2 gap-4 my-4">
`;

for (const dir of dirs) {
  content += `
  <a href="/${dir.toLowerCase()}" class="block p-4 border rounded hover:bg-gray-50 dark:hover:bg-gray-800 transition">
    <h3 class="font-bold text-lg mb-1">${dir}</h3>
    <p class="text-sm text-gray-500">Browse ${dir}</p>
  </a>
`;
}

content += `</div>\n\n## Recent Notes\n\n`;

for (const file of recentFiles) {
  // Calculate relative path for link
  // Note: This is a rough approx, assuming standard obsidian-style unique filenames or simple paths
  // For Lithos, we usually want the wikilink or absolute path relative to content
  // specific link generation depends on router, but [[Note Name]] works with transform
  content += `- [[${file.name}]]\n`;
}

// 4. Write File
writeFileSync(indexPath, content);
console.log(`[generate-index] Created index.md with ${dirs.length} spaces and ${recentFiles.length} recent notes.`);
